### ISSUE TITLE
`header_case` rule

### ISSUE THREAD

**Issue by TheAwiteb** [welpo/git-sumi#17]
# Feature Request

## Summary

A rule like `description_case` but for the header, where can specify a specific case for the first letter in the header

## Motivation

This will help to make the change log and the log history looks better, same as `description_case`

## Detailed Description

This should respect the conventional commits header, which in this case it will check the header not the type

## Contributing request
I can work on this if it's accepted

**Comment by TheAwiteb** [comment]
Sorry, looks like `description_case` is for the header. I though is for the body

**Comment by welpo** [comment]
I appreciate the intention to contribute!

Reviewing the Rules docs, one could easily be confused by the use of "description" without more context.

I've added (f5c7074) a little "info" section referring to the FAQ for the commit part.

Thanks!
